name: github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Install Vagrant and libvirt
      - run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vagrant
          sudo apt-get install -y build-essential qemu-kvm qemu-utils libvirt-dev libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager dnsmasq
          sudo vagrant plugin install vagrant-libvirt
      - run: node --version
      - run: yarn --version
      - run: dotnet --version
      - run: vagrant --version
      - run: sudo vagrant up
      - run: sudo vagrant ssh -c "echo 'hello world!'"
      - run: sudo vagrant destroy -f
